apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: perf-results
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.elastic.syncWave | quote }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination: 
    namespace: perf-results
    server: https://kubernetes.default.svc
  source:
    repoURL: {{ .Values.global.repo.url }}
    path: charts/elasticsearch
    revision: {{ .Values.global.repo.branch }}
    helm:
      releaseName: perf-results
{{- with .Values.elastic.values }}
      values: |-
{{- toYaml . | indent 8 }}
{{- end }}
      parameters:
      - name: fullnameOverride
        value: perf-results
      - name: ingress.hostName
        value: perf-results
      - name: ingress.baseDomain
        value: {{ .Values.global.baseDomain }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true