apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: results
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.elastic.syncWave | quote }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination: 
    namespace: elastic-results
    server: https://kubernetes.default.svc
  source:
    repoURL: {{ .Values.global.repo.url }}
    path: charts/elasticsearch
    revision: {{ .Values.global.repo.branch }}
    helm:
      releaseName: airflow
{{- with .Values.elastic.values }}
      values: |-
{{- toYaml . | indent 8 }}
{{- end }}        
  syncPolicy:
    automated:
      prune: true
      selfHeal: true