aggregator:
  configMap: elasticsearch-output
  extraEnv:
  - name: ELASTICSEARCH_HOST
    value: quickstart-es-http.elastic.svc.cluster.local
  - name: ELASTICSEARCH_PORT
    value: "9200"
forwarder:
  configMap: custom-parser
  rbac:
    pspEnabled: true
  containerSecurityContext:
    privileged: true
    allowPrivilegeEscalation: true
  extraEnv:
  - name: FLUENTD_UID
    value: '0'
